
Welcome to MINIME !

Available boot options:
label_gnome                    - Start MINIME Linux in Gnome
label_kde                      - Start MINIME Linux in KDE
label_cde                      - Start MINIME Linux in CDE
label_nohome                   - Start MINIME Linux in CDE without persistent home
label_overlay                  - Start MINIME Linux in CDE with persistent overlay support
label_nuke_manual              - Start Disk Nuke in manual mode
label_nuke_auto                - Start Disk Nuke in auto mode, EXTREAMLLY DANGEROUS!!!
label_dos                      - Start DOS
label_harddisk                 - Local boot from hard disk
label_memtest                  - Run Memory Test
label_hdt                      - Run Hardware Test


