
Welcome to MINIME !

Available boot options:
label_gnome                    - Start MINIME Linux in GNOME
label_kde                      - Start MINIME Linux in KDE
label_nohome                   - Start MINIME Linux in GNOME without persistent home
label_overlay                  - Start MINIME Linux in GNOME with persistent overlay support
label_nuke_manual              - Start Disk Nuke in manual mode
label_nuke_auto                - Start Disk Nuke in auto mode, EXTREAMLLY DANGEROUS!!!
label_dos                      - Start DOS
label_harddisk                 - Local boot from hard disk
label_memtest                  - Run Memory Test
label_hdt                      - Run Hardware Test


