
Welcome to MINIME !

Available boot options:
label_kde                      - Start MINIME Linux in KDE
label_gnome                    - Start MINIME Linux in GNOME
label_nohome                   - Start MINIME Linux in KDE without persistent home
label_overlay                  - Start MINIME Linux in KDE with persistent overlay
label_ram                      - Start MINIME Linux in RAM
label_pe_x86                   - Run Windows PE(x86)
label_pe_x64                   - Run Windows PE(x64)
label_nuke_manual              - Start Disk Nuke in manual mode
label_nuke_auto                - Start Disk Nuke in auto mode, EXTREAMLLY DANGEROUS!!!
label_dos                      - Start DOS
label_harddisk                 - Local boot from hard disk
label_plpbt                    - Run Plot boot manager
label_memtest                  - Run Memory Test
label_hdt                      - Run Hardware Test

